#!/bin/bash


################################################################################
# Name: Jose-Antonio D. Rubio
# OSUID: 932962915
# Class: 344-400
# Program 4 OTP - compileall 
###############################################################################

gcc -o keygen keygen.c
gcc -o otp_dec otp_dec.c
gcc -o otp_dec_d otp_dec_d.c
gcc -o otp_enc otp_enc.c
gcc -o otp_enc_d otp_enc_d.c



